import Head from "next/head";
import HomepageLayout from "../layouts/HomepageLayout";
import "../styles/Home.module.scss";

export default function Homepage() {
  return (
    <>
      <Head>
        <title>Listenext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageLayout />
    </>
  );
}
