import Head from "next/head";
import HomepageLayout from "../../layouts/HomepageLayout";
import "../../styles/Home.module.scss";

export const getStaticProps = async () => {
  const res = await fetch("https://api.deezer.com/genre/0/artists");
  const resData = await res.json();
  return {
    props: {
      reccomendedArtists: resData.data,
    },
  };
};

export default function Homepage(props) {
  return (
    <>
      <Head>
        <title>Listenext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageLayout {...props} />
    </>
  );
}
